export const CHECK__REQUEST = "CHECK__REQUEST";
export const CHECK__SUCCESS = "CHECK__SUCCESS";
export const CHECK__FAIL = "CHECK__FAIL";
export const REFRESH__TOKEN_REQUEST = "REFRESH__TOKEN_REQUEST";
export const REFRESH__TOKEN_SUCCESS = "REFRESH__TOKEN_SUCCESS";
export const REFRESH__TOKEN_FAIL = "REFRESH__TOKEN_FAIL";
