export const CATALOG_LIST_REQUEST = "CATALOG_LIST_REQUEST";
export const CATALOG_LIST_SUCCESS = "CATALOG_LIST_SUCCESS";
export const CATALOG_LIST_FAIL = "CATALOG_LIST_FAIL";
export const CATALOG_ADD_REQUEST = "CATALOG_ADD_REQUEST";
export const CATALOG_ADD_SUCCESS = "CATALOG_ADD_SUCCESS";
export const CATALOG_ADD_FAIL = "CATALOG_ADD_FAIL";
